const DISPUTE_STATUS_OPEN = "open";
const DISPUTE_STATUS_IN_REVIEW = "in_review";
const DISPUTE_STATUS_RESOLVED = "resolved";
const DISPUTE_STATUS_CLOSED = "closed";

const DISPUTE_STATUSES = [
  DISPUTE_STATUS_OPEN,
  DISPUTE_STATUS_IN_REVIEW,
  DISPUTE_STATUS_RESOLVED,
  DISPUTE_STATUS_CLOSED,
];

const OPEN_DISPUTE_STATUSES = [DISPUTE_STATUS_OPEN, DISPUTE_STATUS_IN_REVIEW];

module.exports = {
  DISPUTE_STATUS_OPEN,
  DISPUTE_STATUS_IN_REVIEW,
  DISPUTE_STATUS_RESOLVED,
  DISPUTE_STATUS_CLOSED,
  DISPUTE_STATUSES,
  OPEN_DISPUTE_STATUSES,
};
