require('dotenv').config();

module.exports = {
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_REGION: process.env.AWS_REGION,
  AWS_S3_BUCKET: process.env.AWS_S3_BUCKET,
  LOCAL_IMAGE_DIR: process.env.LOCAL_IMAGE_DIR,
  /** No trailing slash. Used to turn stored keys/paths into full image URLs in API JSON. */
  IMAGE_CDN_BASE_URL: process.env.IMAGE_CDN_BASE_URL || process.env.CDN_BASE_URL,
  NODE_ENV: process.env.NODE_ENV,  // 'production' or 'development'
  RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET,
  RAZORPAY_WEBHOOK_SECRET: process.env.RAZORPAY_WEBHOOK_SECRET,
  /** Public URL Razorpay can reach (ngrok/production host) — separate from Postman `baseUrl`. */
  RAZORPAY_BASE_URL: process.env.RAZORPAY_BASE_URL,
  WHATSAPP_ENABLED: process.env.WHATSAPP_ENABLED === 'true',
  WHATSAPP_OTP_DEV_FALLBACK: process.env.WHATSAPP_OTP_DEV_FALLBACK === 'true',
  WHATSAPP_API_VERSION: process.env.WHATSAPP_API_VERSION || 'v22.0',
  WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
  WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,
  WHATSAPP_OTP_TEMPLATE_NAME: process.env.WHATSAPP_OTP_TEMPLATE_NAME,
  WHATSAPP_OTP_TEMPLATE_LANGUAGE: process.env.WHATSAPP_OTP_TEMPLATE_LANGUAGE || 'en',
  WHATSAPP_OTP_EXPIRY_MINUTES: Number(process.env.WHATSAPP_OTP_EXPIRY_MINUTES || 10),
  WHATSAPP_OTP_INCLUDE_COPY_BUTTON: process.env.WHATSAPP_OTP_INCLUDE_COPY_BUTTON === 'true',
  WHATSAPP_WEBHOOK_VERIFY_TOKEN: process.env.WHATSAPP_WEBHOOK_VERIFY_TOKEN,
  WHATSAPP_APP_SECRET: process.env.WHATSAPP_APP_SECRET,
  WHATSAPP_WEBHOOK_SKIP_SIGNATURE_VERIFY:
    process.env.WHATSAPP_WEBHOOK_SKIP_SIGNATURE_VERIFY === 'true',
  EMAIL_OTP_DEV_FALLBACK: process.env.EMAIL_OTP_DEV_FALLBACK === 'true',
  APPLE_IAP_ISSUER_ID: process.env.APPLE_IAP_ISSUER_ID || 'a58b18f5-a60e-444c-8d0e-2bbd3ce2da9d',
  APPLE_IAP_KEY_ID: process.env.APPLE_IAP_KEY_ID || 'GX8FQCRN5C',
  APPLE_IAP_PRIVATE_KEY: process.env.APPLE_IAP_PRIVATE_KEY,
  APPLE_IAP_PRIVATE_KEY_PATH: process.env.APPLE_IAP_PRIVATE_KEY_PATH,
  APPLE_IAP_BUNDLE_ID: process.env.APPLE_IAP_BUNDLE_ID || 'com.partnerapp.helppr',
  APPLE_IAP_APP_APPLE_ID: process.env.APPLE_IAP_APP_APPLE_ID,
  APPLE_IAP_ENVIRONMENT: process.env.APPLE_IAP_ENVIRONMENT,
};